### ISSUE TITLE
Review, chapter numbering

### ISSUE THREAD

**Issue by vr8hub** [jobcurtis/upton-sinclair_king-coal#2]
@acabal, the section numbering in book 4 is off, both in the scans and the transcription; it skips straight from 15 to 17, and there are two 19's. Job asked about this during the production, and was advised to keep it. I've checked three "modern" (non-PD) editions that are on IA, and two of the three fix the numbering. I had a similar circumstance in _Le Morte d’Arthur_ and I corrected it. I don't see any reason to keep an incorrect numbering; there's no evidence of it being intentional.

What do you say?

**Comment by acabal** [comment]
OK, let's correct it then.

**Comment by jobcurtis** [comment]
Sounds good, this has been done. I assume it's an editorial change as it's fixing a printer error.
