### ISSUE TITLE
Re-review

### ISSUE THREAD

**Issue by vr8hub** [jobcurtis/upton-sinclair_king-coal#3]
- [x] The lint error in chapter-3-3 being suppressed in the ignore file is an actual error that should be corrected. The text says "…slugged Or shot…" (capital Or) instead of "…slugged or shot…". Lint has false positives (see the chapter-1-3 one), but they are few and far between, and we ignore it at our peril. :)
- [x] We don't use the relative keywords (small, large, etc.), or percentages when it comes to font-sizes, just fractions of an em. I think .85em is going to be in the ballpark, but you can play with it.

**Comment by jobcurtis** [comment]
Thanks @vr8hub, resolved those in d026a39 and 638a9a0 respectively.

Good catch on the lint issue, I thought it was referring to `“And no trouble for them`.

**Comment by vr8hub** [comment]
I suspected that. :) That's what I meant by ignoring it–it's very rarely wrong, so if we _think_ it's wrong, we need to look closer. (Yes, I have to say this to myself quite often!)
